database:
  sql:
    user:
      select:
        byEmail: "SELECT * FROM USERS WHERE EMAIL = :EMAIL AND TYPE = :TYPE"
        byId: "SELECT * FROM USERS WHERE EMAIL = :EMAIL AND PASSWORD = :PASSWORD AND TYPE = :TYPE"
        all: ""
      insert:
        newUser: "INSERT INTO USERS (NAME, EMAIL, PASSWORD, TYPE) VALUES (:NAME, :EMAIL, :PASSWORD, :TYPE)"
      update:
        userDetails: ""
      delete:
        byId: ""
    tournament:
      select:
        byId: ""
        all: ""
      insert:
        newTournament: ""
      update:
        tournamentDetails: ""
      delete:
        byId: ""
