database:
  sql:
    user:
      select:
        byMobileNumber: ""
        byId: "SELECT * FROM USERS WHERE EMAIL = :EMAIL AND PASSWORD = :PASSWORD"
        all: ""
      insert:
        newUser: "INSERT INTO USERS (NAME, EMAIL, PASSWORD, TYPE) VALUES (NAME, :EMAIL, :PASSWORD, :TYPE)"
      update:
        userDetails: ""
      delete:
        byId: ""
    tournament:
      select:
        byId: ""
        all: ""
      insert:
        newTournament: ""
      update:
        tournamentDetails: ""
      delete:
        byId: ""
